services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # Use Dockerfile.dev for development, or Dockerfile for production
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mount entire backend for hot reload
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Use Dockerfile.dev for development, or Dockerfile for production
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_DEV_API=http://localhost:8000
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./frontend:/app # Mount your source code
      - /app/node_modules # Prevents node_modules from being overwritten by the container
      - uploads:/uploads:ro

volumes:
  postgres_data:
  uploads:
