services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod # Use Dockerfile.dev for development, or Dockerfile for production
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Use Dockerfile.dev for development, or Dockerfile for production
    depends_on:
      - postgres
    ports:
      - "3000:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
