version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # or your production Dockerfile if needed
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
