"""added relationship in users and professor take 2

Revision ID: 16289ff72f97
Revises: 38e3d4b7a673
Create Date: 2025-04-09 09:51:06.938051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateTable, DropTable


# revision identifiers, used by Alembic.
revision: str = '16289ff72f97'
down_revision: Union[str, None] = '38e3d4b7a673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint("users_professor_id_fkey", type_="foreignkey")
    
    with op.batch_alter_table("users") as batch_op:
        batch_op.create_foreign_key(
            "users_professor_id_fkey",
            "professor_information",
            ["professor_id"],
            ["professor_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
