"""deleting test tables

Revision ID: 270478634956
Revises: 0e2d559b9302
Create Date: 2025-04-29 14:24:17.173486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270478634956'
down_revision: Union[str, None] = '0e2d559b9302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_table2_id', table_name='test_table2')
    op.drop_table('test_table2')
    op.drop_index('ix_test_table_id', table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.create_index('ix_test_table_id', 'test_table', ['id'], unique=False)
    op.create_table('test_table2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table2_pkey')
    )
    op.create_index('ix_test_table2_id', 'test_table2', ['id'], unique=False)
    # ### end Alembic commands ###
