"""added new columns in user table

Revision ID: 4f637645cc74
Revises: 061a5bd7e924
Create Date: 2025-04-09 08:00:00.931867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f637645cc74'
down_revision: Union[str, None] = '061a5bd7e924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default=sa.text('professor')))
    op.add_column('users', sa.Column('professor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'professor_information', ['professor_id'], ['professor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'professor_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
