"""added map table

Revision ID: 664674331ab5
Revises: 74feb7958983
Create Date: 2025-04-09 18:14:26.170258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664674331ab5'
down_revision: Union[str, None] = '74feb7958983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('floor_level', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_images_id'), 'map_images', ['id'], unique=False)
    op.drop_table('alembic_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='alembic_test_pkey')
    )
    op.drop_index(op.f('ix_map_images_id'), table_name='map_images')
    op.drop_table('map_images')
    # ### end Alembic commands ###
