"""test

Revision ID: 6ed9075421e9
Revises: f55807894749
Create Date: 2025-04-29 14:02:31.552830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed9075421e9'
down_revision: Union[str, None] = 'f55807894749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_table_id'), 'test_table', ['id'], unique=False)
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'created_at')
    op.drop_index(op.f('ix_test_table_id'), table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###
