"""adding suggested start and end time columns in appointment table

Revision ID: c8c8b740cf5b
Revises: f981643dde3b
Create Date: 2025-05-03 06:04:38.098501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c8b740cf5b'
down_revision: Union[str, None] = 'f981643dde3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('suggested_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('suggested_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'suggested_end_time')
    op.drop_column('appointments', 'suggested_start_time')
    # ### end Alembic commands ###
