"""adding user_faq table

Revision ID: f4a6577dccf5
Revises: 923749be317a
Create Date: 2025-04-29 07:45:48.025040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a6577dccf5'
down_revision: Union[str, None] = '923749be317a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_faq_id'), 'user_faq', ['id'], unique=False)
    op.drop_index('ix_map_images_id', table_name='map_images')
    op.drop_table('map_images')
    op.drop_table('alembic_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='alembic_test_pkey')
    )
    op.create_table('map_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('floor_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='map_images_pkey')
    )
    op.create_index('ix_map_images_id', 'map_images', ['id'], unique=False)
    op.drop_index(op.f('ix_user_faq_id'), table_name='user_faq')
    op.drop_table('user_faq')
    # ### end Alembic commands ###
