"""adding created_at column in appointment table

Revision ID: f55807894749
Revises: f4a6577dccf5
Create Date: 2025-04-29 13:48:35.881561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55807894749'
down_revision: Union[str, None] = 'f4a6577dccf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('users_professor_id_fkey1', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_professor_id_fkey1', 'users', 'professor_information', ['professor_id'], ['professor_id'])
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###
