"""adding isPinned column in faq table

Revision ID: f981643dde3b
Revises: 270478634956
Create Date: 2025-04-30 11:46:48.645302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f981643dde3b'
down_revision: Union[str, None] = '270478634956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq', sa.Column('isPinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq', 'isPinned')
    # ### end Alembic commands ###
